// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldqgdpsefrpvvuruvozm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkcWdkcHNlZnJwdnZ1cnV2b3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTgzNzksImV4cCI6MjA2MzEzNDM3OX0.ponGdAVL0_zv2V5FUF7eAC0TO4DAgaO3Yu63GrE80i8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);